initial_joint_positions:
  panda_arm:
    joint1: 0.0
    joint2: 0.0      # Was -0.785. Set to 0.0 to stand upright.
    joint3: 0.0
    joint4: -1.57    
    joint5: 0.0
    joint6: 1.57     
    joint7: 0.785
  panda_gripper:
    joint1: 0.0
    joint2: 0.0
